CREATE SEQUENCE container_table_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE itemtype_table_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE tags_table_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE item_table_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE typeattributes_table_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE containeritem_table_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE itemattributes_table_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE itemtag_table_seq START WITH 1 INCREMENT BY 50;