name: Docker Creation

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  versioning-master:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Increment version in package.json
        run: npm version minor
        working-directory: ./src/main/frontend

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git add package-lock.json
          git commit -m "Incremented version to $(node -p "require('./package.json').version")"
          git push origin master --tags
        working-directory: ./src/main/frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create Public Key
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        run: |
          echo "$PUBLIC_KEY" > ./public.key

      - name: Install Dependencies and Build React App
        run: |
          npm ci
          npm run build
        working-directory: ./src/main/frontend

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up docker.env file
        run: |
          echo "${{ secrets.DOCKER_ENV }}" > src/main/resources/docker.env

      - name: Build Spring Boot Jar File
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Version Number
        id: get_version
        run: |
          VERSION=$(jq -r .version < src/main/frontend/package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker image build -t ghcr.io/$REPO_NAME:${{ env.VERSION }} \
                             -t ghcr.io/$REPO_NAME:latest .
          docker push ghcr.io/$REPO_NAME:${{ env.VERSION }}
          docker push ghcr.io/$REPO_NAME:latest
